name: Release Workflow

on:
  push:
    branches:
      - main
      - master
      - actions

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Extracting previous version
        id: previous_version
        run: echo prev_version=$(git describe --abbrev=0 --tags) >> $GITHUB_STATE

      - name: Extract current version
        id: current_version
        run: echo current_version=$(node -e "console.log(require('./package.json').version)") >> $GITHUB_STATE

      - name: Check if the version changed
        id: version_changed
        run: echo changed=$(test "${{ steps.current_version.outputs.curr_version }}" != "${{ steps.previous_version.outputs.prev_version }}") >> $GITHUB_STATE

      - name: Show result
        run: echo $changed
